### ISSUE TITLE
npm install won't run successfully - latest commit is broken

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-explorer#34]
I'm trying to install ark-explorer on a machine that's currently running ark-node and arkstats. I'm running npm 3.10.10 and node 6.9.5. `npm install` fails for me and complains about not having root privileges: https://gist.github.com/vmunich/d37af168a18848cef913b8131a8ccbd1

So I ran sudo npm install and it gave out this errror:
```
└── UNMET PEER DEPENDENCY @angular/core@4.4.6

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ngx-socket-io@1.0.8 requires a peer of @angular/core@^5.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
root@darkland:~/ark-explorer# clear
root@darkland:~/ark-explorer# npm install

> canvas@1.6.7 install /home/darkland/ark-explorer/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
./util/has_lib.sh: 31: ./util/has_lib.sh: pkg-config: not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/darkland/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/darkland/.nvm/versions/node/v6.9.5/bin/node" "/home/darkland/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/darkland/ark-explorer/node_modules/canvas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ngx-socket-io@1.0.8 requires a peer of @angular/core@^5.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
root@darkland:~/ark-explorer#
```

This time, it did not generate a npm-debug.log. Any suggestions? 
```
root@darkland:~/ark-explorer# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by vmunich** [comment]
Just reporting back, something is messed up on the latest commit. I went back to https://github.com/ArkEcosystem/ark-explorer/commit/e365e666c8fa6f9435d2884bba86c231a23bc93b and everything is working as expected.

**Comment by vmunich** [comment]
It compiles successfully up to this merge: https://github.com/ArkEcosystem/ark-explorer/commit/ee6c88120260e5348b6595fb4821f75390b25a6c

On the latest merge (https://github.com/ArkEcosystem/ark-explorer/commit/99e3b892edc5aae5cf3946ef65981face5997ea9), it fails:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ch                                   okidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                   1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                   )
npm WARN ngx-socket-io@1.0.8 requires a peer of @angular/core@^5.0.0 but none wa                                   s installed.
darkland@darkland:~/ark-explorer$ ng serve --host=0.0.0.0 --disable-host-check
WARNING Running a server with --disable-host-check is a security risk. See https                                   ://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a                                    for more information.
** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on                                    http://localhost:4200 **
Date: 2017-11-22T20:15:39.052Z                                                                                     Hash: 235fbac51ffae2b54ce1
Time: 13864ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [                                   rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 534 kB {vendor} [initial]                                    [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 217 k                                   B {inline} [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 200 kB {inlin                                   e} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 91.6 kB {inline}                                    [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.22 MB [initial]                                    [rendered]

ERROR in /home/darkland/ark-explorer/src/app/pages/address/address.component.ts                                    (50,48): Property 'supplyChoosen$' does not exist on type 'CurrencyService'.

webpack: Failed to compile.
```

**Comment by vmunich** [comment]
Fixed the typo breaking it https://github.com/ArkEcosystem/ark-explorer/pull/35
